version: '3.8'

networks:
  doris-ranger-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# Volumes are now using bind mounts from ./data directory

services:
  # PostgreSQL Database for Ranger (using official Ranger DB image)
  ranger-db:
    image: apache/ranger-db:2.7.0
    platform: linux/amd64
    container_name: ranger-db
    hostname: ranger-db.example.com
    networks:
      doris-ranger-network:
        ipv4_address: 172.20.0.10
    ports:
      - "5433:5432"
    restart: always
    healthcheck:
      test: ["CMD", "su", "-c", "pg_isready -q", "postgres"]
      interval: 10s
      timeout: 2s
      retries: 30

  # Apache Solr for Ranger Audit
  ranger-solr:
    image: apache/ranger-solr:2.7.0
    platform: linux/amd64
    container_name: ranger-solr
    hostname: ranger-solr.example.com
    networks:
      doris-ranger-network:
        ipv4_address: 172.20.0.11
    ports:
      - "8983:8983"
    restart: always
    command: ["solr-precreate", "ranger_audits", "/opt/solr/server/solr/configsets/ranger_audits/"]

  # Zookeeper for Ranger
  ranger-zk:
    image: apache/ranger-zk:2.7.0
    platform: linux/amd64
    container_name: ranger-zk
    hostname: ranger-zk.example.com
    networks:
      doris-ranger-network:
        ipv4_address: 172.20.0.12
    ports:
      - "2181:2181"
    restart: always

  # Apache Ranger Admin
  ranger:
    image: apache/ranger:2.7.0
    platform: linux/amd64
    container_name: ranger
    hostname: ranger.example.com
    environment:
      RANGER_VERSION: 2.7.0
      RANGER_DB_TYPE: postgres
      # LDAP Authentication Configuration
      RANGER_AUTHENTICATION_METHOD: LDAP
      RANGER_LDAP_URL: ldap://openldap:389
      RANGER_LDAP_USER_DN_PATTERN: uid={0},ou=users,dc=example,dc=com
      RANGER_LDAP_GROUP_SEARCH_BASE: ou=groups,dc=example,dc=com
      RANGER_LDAP_GROUP_SEARCH_FILTER: (member={0})
      RANGER_LDAP_GROUP_ROLE_ATTRIBUTE: cn
      RANGER_LDAP_BASE_DN: dc=example,dc=com
      RANGER_LDAP_BIND_DN: cn=admin,dc=example,dc=com
      RANGER_LDAP_BIND_PASSWORD: admin123
      RANGER_LDAP_REFERRAL: follow
      RANGER_LDAP_USER_SEARCH_FILTER: (uid={0})
      RANGER_LDAP_DEFAULT_ROLE: ROLE_USER
    networks:
      doris-ranger-network:
        ipv4_address: 172.20.0.20
    ports:
      - "6080:6080"
    volumes:
      - ./ranger-config/ranger-doris-plugin-3.0.0-SNAPSHOT.jar:/opt/ranger/ranger-2.7.0-admin/ews/webapp/WEB-INF/classes/ranger-plugins/doris/ranger-doris-plugin-3.0.0-SNAPSHOT.jar:ro
      - ./ranger-config/mysql-connector-java-8.0.25.jar:/opt/ranger/ranger-2.7.0-admin/ews/webapp/WEB-INF/classes/ranger-plugins/doris/mysql-connector-java-8.0.25.jar:ro
      - ./ranger-config/ranger-servicedef-doris.json:/opt/ranger-config/ranger-servicedef-doris.json:ro
      - ./ranger-config/ranger-startup.sh:/opt/ranger-startup.sh:ro
    depends_on:
      ranger-db:
        condition: service_healthy
      ranger-solr:
        condition: service_started
      ranger-zk:
        condition: service_started
      openldap:
        condition: service_started
    command: ["/bin/bash", "/opt/ranger-startup.sh"]
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6080/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s

  # OpenLDAP Server
  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    hostname: ldap.example.com
    environment:
      - LDAP_ORGANISATION=Example Organization
      - LDAP_DOMAIN=example.com
      - LDAP_BASE_DN=dc=example,dc=com
      - LDAP_ADMIN_PASSWORD=admin123
      - LDAP_CONFIG_PASSWORD=config123
      - LDAP_RFC2307BIS_SCHEMA=true
      - LDAP_BACKEND=mdb
      - LDAP_TLS=true
      - LDAP_TLS_CRT_FILENAME=ldap.crt
      - LDAP_TLS_KEY_FILENAME=ldap.key
      - LDAP_TLS_CA_CRT_FILENAME=ca.crt
      - LDAP_TLS_ENFORCE=false
      - LDAP_TLS_VERIFY_CLIENT=never
      - LDAP_REPLICATION=false
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=false
      - LDAP_SSL_HELPER_PREFIX=ldap
    volumes:
      - ./data/ldap/data:/var/lib/ldap
      - ./data/ldap/config:/etc/ldap/slapd.d
      - ./ldap-config/ldap-init.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/ldap-init.ldif
    ports:
      - "389:389"
      - "636:636"
    networks:
      doris-ranger-network:
        ipv4_address: 172.20.0.50
    restart: always

  # phpLDAPadmin for LDAP management UI
  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    hostname: phpldapadmin.example.com
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - "6443:443"
      - "6081:80"
    networks:
      doris-ranger-network:
        ipv4_address: 172.20.0.51
    depends_on:
      - openldap
    restart: always

  # Apache Ranger UserSync - now enabled for LDAP sync
  # Note: There's no official separate UserSync image, we need to use a custom solution
  ranger-usersync:
    image: ubuntu:22.04
    platform: linux/amd64
    container_name: ranger-usersync
    hostname: ranger-usersync.example.com
    environment:
      # LDAP Configuration
      SYNC_SOURCE: ldap
      SYNC_LDAP_URL: ldap://openldap:389
      SYNC_LDAP_BIND_DN: cn=admin,dc=example,dc=com
      SYNC_LDAP_BIND_PASSWORD: admin123
      SYNC_LDAP_USER_SEARCH_BASE: ou=users,dc=example,dc=com
      SYNC_GROUP_SEARCH_BASE: ou=groups,dc=example,dc=com
      POLICY_MGR_URL: http://ranger:6080
      RANGER_ADMIN_USERNAME: admin
      RANGER_ADMIN_PASSWORD: rangerR0cks!
    volumes:
      - ./ranger-config/ldap-sync-script.sh:/opt/ldap-sync-script.sh:ro
    command: ["/bin/bash", "-c", "apt-get update && apt-get install -y ldap-utils curl jq && while true; do bash /opt/ldap-sync-script.sh; sleep 30; done"]
    networks:
      doris-ranger-network:
        ipv4_address: 172.20.0.21
    depends_on:
      ranger:
        condition: service_healthy
      openldap:
        condition: service_started

  # Apache Ranger TagSync (optional - can be added later)
  # ranger-tagsync:
  #   image: apache/ranger-tagsync:2.7.0
  #   platform: linux/amd64
  #   container_name: ranger-tagsync
  #   hostname: ranger-tagsync.example.com
  #   environment:
  #     RANGER_VERSION: 2.7.0
  #   networks:
  #     doris-ranger-network:
  #       ipv4_address: 172.20.0.22
  #   depends_on:
  #     ranger:
  #       condition: service_healthy

  # Apache Doris Frontend (FE)
  doris-fe-01:
    image: dyrnq/doris:3.0.5
    platform: linux/amd64
    container_name: doris-fe-01
    hostname: doris-fe-01
    environment:
      - TZ=Asia/Kolkata
      - RUN_MODE=FE
      - FE_SERVERS=doris-fe-01:172.20.0.30:9010
      - FE_ID=1
      - ENABLE_FQDN_MODE=true
      # LDAP Configuration for Doris
      - LDAP_HOST=openldap
      - LDAP_PORT=389
      - LDAP_ADMIN_DN=cn=admin,dc=example,dc=com
      - LDAP_ADMIN_PASSWORD=admin123
      - LDAP_USER_BASE_DN=ou=users,dc=example,dc=com
      - LDAP_GROUP_BASE_DN=ou=groups,dc=example,dc=com
    ports:
      - "8031:8030"
      - "9031:9030"
    volumes:
      - ./data/fe-01-meta:/opt/apache-doris/fe/doris-meta
      - ./data/fe-01-log:/opt/apache-doris/fe/log
      - ./doris-config/fe/fe.conf:/tmp/custom-fe.conf:ro
      - ./doris-config/fe/ldap.conf:/tmp/ldap.conf:ro
      - ./doris-config/fe/ranger-doris-security.xml:/tmp/ranger-doris-security.xml:ro
      - ./doris-config/fe/ranger-doris-audit.xml:/tmp/ranger-doris-audit.xml:ro
      - ./doris-config/fe/log4j.properties:/tmp/log4j.properties:ro
      - ./ranger-config/ranger-doris-plugin-3.0.0-SNAPSHOT.jar:/tmp/ranger-doris-plugin-3.0.0-SNAPSHOT.jar:ro
      - ./ranger-config/mysql-connector-java-8.0.25.jar:/tmp/mysql-connector-java-8.0.25.jar:ro
      - ./doris-config/fe-entrypoint.sh:/custom-entrypoint.sh:ro
    entrypoint: ["/bin/bash", "/custom-entrypoint.sh"]
    networks:
      doris-ranger-network:
        ipv4_address: 172.20.0.30
    restart: always
    logging:
      options:
        max-size: '500m'

  # Apache Doris Backend (BE)
  doris-be-01:
    image: dyrnq/doris:3.0.5
    platform: linux/amd64
    container_name: doris-be-01
    hostname: doris-be-01
    environment:
      - TZ=Asia/Kolkata
      - RUN_MODE=BE
      - FE_SERVERS=doris-fe-01:172.20.0.30:9010
      - BE_ADDR=172.20.0.31:9050
      - ENABLE_FQDN_MODE=true
      - MYSQL_PWD=root
      - WAIT4X_MYSQL_DSN=root:root@tcp(172.20.0.30:9030)/
    ports:
      - "8041:8040"
    volumes:
      - ./data/be-01-storage:/opt/apache-doris/be/storage
      - ./data/be-01-log:/opt/apache-doris/be/log
      - ./doris-config/be/be.conf:/tmp/custom-be.conf:ro
      - ./doris-config/be-entrypoint.sh:/custom-entrypoint.sh:ro
    entrypoint: ["/bin/bash", "/custom-entrypoint.sh"]
    depends_on:
      - doris-fe-01
    networks:
      doris-ranger-network:
        ipv4_address: 172.20.0.31
    restart: always
    ulimits:
      nofile:
        soft: 655350
        hard: 655350
      memlock:
        soft: -1
        hard: -1
    privileged: true
    logging:
      options:
        max-size: '500m'

  # Optional: Additional Doris Backend nodes can be added here
  # doris-be-2:
  #   image: apache/doris:2.1.0-be
  #   container_name: doris-be-2
  #   hostname: doris-be-2
  #   environment:
  #     FE_SERVERS: fe1:doris-fe:9010
  #     BE_ADDR: doris-be-2:9050
  #     PRIORITY_NETWORKS: 172.20.0.0/16
  #     NODE_ROLE: ""
  #   volumes:
  #     - doris_be2_storage:/opt/apache-doris/be/storage
  #     - doris_be2_log:/opt/apache-doris/be/log
  #     - ./doris-config/be/be.conf:/opt/apache-doris/be/conf/be.conf
  #   networks:
  #     doris-ranger-network:
  #       ipv4_address: 172.20.0.32
  #   ports:
  #     - "8041:8040"
  #     - "9051:9050"
  #     - "9061:9060"
  #     - "8061:8060"
  #   depends_on:
  #     doris-fe:
  #       condition: service_healthy